# .github/workflows/code-quality.yml
name: Code Quality

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort bandit safety
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Check formatting with Black
        run: black --check src tests

      - name: Check imports with isort
        run: isort --check-only --profile black src tests

      - name: Lint with flake8
        run: flake8 src tests

      - name: Security check with Bandit
        run: bandit -r src -x tests

      - name: Dependency security check with Safety
        run: safety check
