name: Data Drift Check

on:
  schedule:
    - cron: '0 2 * * 1' # Run every Monday at 2:00 AM UTC

  workflow_dispatch: # Allows manual runs

jobs:
  data_drift_detection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dominate
          pip install -r requirements.txt
          pip install dvc

      - name: Pull Data with DVC
        run: |
          dvc pull data/processed/train/processed_data.csv.dvc -f
          dvc pull data/processed/test/processed_data.csv.dvc -f

      - name: Run Data Drift Detection Script
        id: drift_check
        # We use 'continue-on-error: true' to ensure the workflow doesn't stop here
        # This allows subsequent steps (like email notification) to run.
        continue-on-error: true
        run: python src/monitoring/data_drift_detection.py

      - name: Upload Drift Report as Artifact
        # This step always runs, regardless of whether drift was found or not.
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: data-drift-report
          path: reports/data_drift/data_drift_report.html

      - name: Send Email Notification if Drift is Detected
        # This step ONLY runs if the 'drift_check' step failed (i.e., script exited with code 1)
        if: steps.drift_check.outcome == 'failure'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com # Use your email provider's SMTP server
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "ALERT: Data Drift Detected in Insurance Prediction Project"
          to: ${{ secrets.RECIPIENT_EMAIL }}
          from: MLOps Pipeline Notifier <${{ secrets.MAIL_USERNAME }}>
          body: |
            Significant data drift was detected during the scheduled check.

            A detailed HTML report has been generated. You can download the 'data-drift-report' artifact from the GitHub Actions run summary page.

            Workflow Run URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

            Please review the report to analyze the drift and decide if model retraining is necessary.

      - name: Fail the Job if Drift was Detected
        # This final step ensures the workflow is marked as "Failed" in the GitHub UI
        if: steps.drift_check.outcome == 'failure'
        run: |
          echo "Failing the workflow because data drift was detected."
          exit 1
