# .github/workflows/model-validation.yml
name: Model Validation

on:
  push:
    branches: [ main, master, develop ]
    paths:
      - 'src/models/**'
      - 'src/features/**'
      - 'src/data/**'
  pull_request:
    branches: [ main, master, develop ]
    paths:
      - 'src/models/**'
      - 'src/features/**'
      - 'src/data/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          
      - name: Download test data
        run: |
          mkdir -p data/raw
          # In a real scenario, you might download test data from a secure location
          # For this example, we'll use dummy data from the repo
          # aws s3 cp s3://your-bucket/test-data.csv data/raw/test.csv
          
      - name: Run data processing pipeline
        run: python -m src.data.process_data --input data/raw/test.csv --output data/processed/test --no-splits
        
      - name: Validate model metrics
        run: |
          # Run a script that loads the model and evaluates it on test data
          # Fails if metrics are below thresholds
          python -m src.models.validate_model --data data/processed/test/processed_data.csv --threshold 0.7