# .github/workflows/model-validation.yml
name: Model Validation

on:
  push:
    branches: [ main, master, develop ]
    paths:
      - 'src/models/**'
      - 'src/features/**'
      - 'src/data/**'
  pull_request:
    branches: [ main, master, develop ]
    paths:
      - 'src/models/**'
      - 'src/features/**'
      - 'src/data/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Prepare test data and model
        run: |
          mkdir -p data/raw data/processed/test models/comparison/production

          # Create test data
          echo "id,Gender,Age,HasDrivingLicense,RegionID,VehicleAge,PastAccident,AnnualPremium,SalesChannelID,DaysSinceCreated,Result" > data/raw/test.csv
          echo "1,Male,30,1,10,1-2 Year,No,1000,26,60,0" >> data/raw/test.csv
          echo "2,Female,25,1,10,< 1 Year,No,1200,26,30,1" >> data/raw/test.csv

          # Create a dummy model
          python scripts/create_dummy_model.py

      - name: Run data processing pipeline
        run: |
          export PYTHONPATH=$GITHUB_WORKSPACE
          python -m src.data.process_data --input data/raw/test.csv --output data/processed/test --no-splits || echo "Data processing skipped"

      - name: Validate model metrics
        run: |
          export PYTHONPATH=$GITHUB_WORKSPACE
          python -m src.models.validate_model --data data/processed/test/processed_data.csv --threshold 0.3
