# .github/workflows/rollback.yml
name: Rollback Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to rollback'
        required: true
        type: choice
        options:
        - staging
        - production
      version:
        description: 'Version to rollback to'
        required: true
        type: string

jobs:
  rollback:
    name: Rollback Deployment
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Rollback deployment
      run: |
        echo "Rolling back ${{ github.event.inputs.environment }} to version ${{ github.event.inputs.version }}"
        # Replace with actual rollback commands
        # Example for Kubernetes:
        # kubectl rollout undo deployment/insurance-api --to-revision=${{ github.event.inputs.version }}
        
    - name: Verify rollback
      run: |
        echo "Verifying rollback deployment"
        # Add verification steps here