# .github/workflows/test.yml
name: Run Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run security tests
        run: |
          # Create a mock model first
          mkdir -p models/comparison/production
          python -c "import pickle; import numpy as np; from sklearn.ensemble import RandomForestClassifier; X = np.random.rand(100, 10); y = np.random.randint(0, 2, 100); model = RandomForestClassifier(n_estimators=10); model.fit(X, y); pickle.dump(model, open('models/comparison/production/production_model.pkl', 'wb'))"

          # Then run the tests
          pytest tests/security -v

      - name: Run integration tests
        run: pytest tests/integration -v

      - name: Run security tests
        run: pytest tests/security -v

      - name: Generate test coverage report
        run: |
          pytest --cov=src --cov-report=xml tests/

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: false
