# .github/workflows/test.yml
name: Run Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Prepare test environment
        run: |
          # Create required directories
          mkdir -p models/comparison/production
          mkdir -p data/raw data/processed/test

          # Create a mock model using the script
          python scripts/create_dummy_model.py

      - name: Run unit tests
        run: |
          export PYTHONPATH=$GITHUB_WORKSPACE
          pytest tests/unit -v

      - name: Run integration tests
        run: |
          export PYTHONPATH=$GITHUB_WORKSPACE
          pytest tests/integration -v

      - name: Run security tests
        run: |
          export PYTHONPATH=$GITHUB_WORKSPACE
          pytest tests/security -v

      - name: Generate test coverage report
        run: |
          export PYTHONPATH=$GITHUB_WORKSPACE
          pytest --cov=src --cov-report=xml tests/

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: false
